name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: vodenje-stroskov/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('vodenje-stroskov/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd vodenje-stroskov
        npm ci

    - name: Build application
      run: |
        cd vodenje-stroskov
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: vodenje-stroskov/build/

  test-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: vodenje-stroskov/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('vodenje-stroskov/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd vodenje-stroskov
        npm ci

    - name: Run tests with coverage
      run: |
        cd vodenje-stroskov
        npm run test:ci

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: vodenje-stroskov/coverage/
