name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [frontend, backend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ${{ matrix.project }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles(matrix.project + '/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ${{ matrix.project }}
      run: npm install

    - name: Build the project
      working-directory: ${{ matrix.project }}
      run: |
        if [ "${{ matrix.project }}" == "backend" ]; then
          npm run build # TypeScript build
        else
          npm run build # React build
        fi
